services:
  - type: web
    name: ska-brb-fight
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: TWITCH_CHANNEL
        value: skavstheworld
      - key: ADMIN_KEY
        sync: false
      - key: TWITCH_BOT_USERNAME
        sync: false
      - key: TWITCH_OAUTH_TOKEN
        sync: false
      - key: OVERLAY_KEY
        sync: false
